---
### Base of this Playbook comes from: https://github.com/jalefkowit/Vagrant-Ansible-Wordpress
- name: Configure Database Servers
  hosts: database_servers
  remote_user: vagrant
  sudo: yes
  gather_facts: no
  tasks:
    - name: Install unzip
      apt: pkg=unzip state=installed update_cache=yes cache_valid_time=3600

    - name: Install MySQL client, server and related libraries
      apt: pkg={{ item }} state=latest
      with_items:
        - mysql-client
        - mysql-server
        - python-mysqldb

    - name: Remove localhost MySQL binding
      lineinfile:
        dest: /etc/mysql/my.cnf
        state: absent
        regexp: "^bind-address"

    - name: Set MySQL bind address
      lineinfile:
        dest: /etc/mysql/my.cnf
        state: present
        regexp: "^bind-address"
        insertafter: '^\[mysqld\]'
        line: "bind-address=0.0.0.0"

    - name: Restart MySQL service
      service:
        name: "mysql"
        state: restarted
        enabled: yes

    - name: Reload MySQL service config
      service:
        name: "mysql"
        state: reloaded
        enabled: yes

    - name: Restart MySQL service
      service:
        name: "mysql"
        state: restarted
        enabled: yes

    - name: Setup MySQL root password
      mysql_user:
        name: "root"
        password: "mysql"
        host: "{{ item }}"
        state: present
      with_items:
        - 127.0.0.1
        - ::1
        - localhost

    - name: Setup MySQL creds for root user
      template:
        src: "templates/mysql"
        dest: "/root/.my.cnf"
        owner: "root"
        mode: 0600

    - name: Delete blank MySQL users
      mysql_user:
        name: ""
        host: "{{ item }}"
        state: absent
      with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost

    - name: Drop MySQL test database
      mysql_db: name=test state=absent
